-- File: db/schema.sql
-- Oracle 26AI Schema for Agentic Reconciliation

-- 1. Tenant Isolation
CREATE TABLE customers (
    customer_id VARCHAR2(50) PRIMARY KEY,
    name VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Invoices
CREATE TABLE invoices (
    invoice_id VARCHAR2(50) PRIMARY KEY,
    customer_id VARCHAR2(50) REFERENCES customers(customer_id),
    vendor_name VARCHAR2(100),
    amount NUMBER(18, 2),
    currency VARCHAR2(3),
    invoice_date DATE,
    due_date DATE,
    po_number VARCHAR2(50),
    status VARCHAR2(20), -- PENDING, PAID, PARTIAL, OVERPAID
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Payments
CREATE TABLE payments (
    payment_id VARCHAR2(50) PRIMARY KEY,
    customer_id VARCHAR2(50) REFERENCES customers(customer_id),
    sender_name VARCHAR2(100),
    amount NUMBER(18, 2),
    currency VARCHAR2(3),
    payment_date DATE,
    payment_rail VARCHAR2(20), -- ACH, WIRE, RTP
    trace_id VARCHAR2(50),
    remittance_raw CLOB, -- Raw text from bank
    status VARCHAR2(20), -- UNMATCHED, MATCHED, PARTIAL_MATCH
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Extracted Remittance Info (JSON Storage)
CREATE TABLE remittance_extractions (
    extraction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id VARCHAR2(50) REFERENCES payments(payment_id),
    customer_id VARCHAR2(50) REFERENCES customers(customer_id),
    extracted_data JSON, -- Oracle 26AI native JSON support
    confidence_score NUMBER(5, 2),
    agent_reasoning CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Reconciliation Matches
CREATE TABLE reconciliation_matches (
    match_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR2(50) REFERENCES customers(customer_id),
    invoice_id VARCHAR2(50) REFERENCES invoices(invoice_id),
    payment_id VARCHAR2(50) REFERENCES payments(payment_id),
    match_type VARCHAR2(30), -- AUTO_1_1, AUTO_MANY_1, MANUAL_OVERRIDE
    confidence_score NUMBER(5, 2),
    explanation CLOB,
    status VARCHAR2(20), -- PROPOSED, FIXED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Vector Embeddings for Semantic Matching (Oracle Vector Search)
CREATE TABLE metadata_vectors (
    vector_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR2(10), -- INVOICE or PAYMENT
    source_id VARCHAR2(50),
    customer_id VARCHAR2(50) REFERENCES customers(customer_id),
    metadata_text CLOB,
    embedding VECTOR(1536, FLOAT32), -- Oracle 26AI VECTOR type (OpenAI embedding size)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. Audit Log (Immutable Trail)
CREATE TABLE audit_trail (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR2(50) REFERENCES customers(customer_id),
    entity_type VARCHAR2(30), -- MATCH, INVOICE, PAYMENT
    entity_id VARCHAR2(50),
    action VARCHAR2(50), -- CREATE_MATCH, OVERRIDE, DELETE
    operator_id VARCHAR2(50), -- system-agent OR user-id
    previous_state JSON,
    new_state JSON,
    agent_version VARCHAR2(20),
    prompt_hash VARCHAR2(64),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_inv_cust ON invoices(customer_id);
CREATE INDEX idx_pay_cust ON payments(customer_id);
CREATE INDEX idx_match_cust ON reconciliation_matches(customer_id);
CREATE INDEX idx_audit_cust ON audit_trail(customer_id);

-- Vector Index (Example)
-- CREATE VECTOR INDEX vidx_metadata ON metadata_vectors(embedding) ORGANIZATION NEIGHBOR PARTITIONS;
